services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: analyticsdb
      MYSQL_USER: analytics
      MYSQL_PASSWORD: analytics_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  db_data: 