version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: analyticsdb
      MYSQL_USER: analytics
      MYSQL_PASSWORD: strong_prod_password
      MYSQL_ROOT_PASSWORD: strong_root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    image: dockerhub-username/analytics-sb-backend:latest
    restart: always
    depends_on:
      - db
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs

  # loki:
  #   image: grafana/loki:2.9.3
  #   restart: always
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml

  # promtail:
  #   image: grafana/promtail:2.9.3
  #   restart: always
  #   volumes:
  #     - ./logs:/var/log/app
  #     - ./promtail-config.yaml:/etc/promtail/config.yaml
  #   command: -config.file=/etc/promtail/config.yaml

  # grafana:
  #   image: grafana/grafana:10.2.3
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=your_strong_grafana_password

volumes:
  db_data: 