services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: analyticsdb
      MYSQL_USER: analytics
      MYSQL_PASSWORD: analytics_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs

  # loki:
  #   image: grafana/loki:2.9.3
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/local-config.yaml

  # promtail:
  #   image: grafana/promtail:2.9.3
  #   volumes:
  #     - ./logs:/var/log/app
  #     - ./promtail-config.yaml:/etc/promtail/config.yaml
  #   command: -config.file=/etc/promtail/config.yaml

  # grafana:
  #   image: grafana/grafana:10.2.3
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=Analytics@2024

volumes:
  db_data: 