apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-backend
  template:
    metadata:
      labels:
        app: analytics-backend
    spec:
      containers:
      - name: analytics-backend
        image: dockerhub-username/analytics-sb-backend:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: analytics-backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: analytics-backend 